apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: cec5-tasks
  name: cec5-tasks
spec:
  lookupPolicy:
    local: false
  tags:
  - name: 0.0-0
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/cec5-tasks-dev/cec5-tasks:0.0-0
    importPolicy: {}
    referencePolicy:
      type: Source